#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "discourse"
name = "Discourse"
description.en = "Discussion platform"
description.fr = "Plateforme de discussion"

version = "2026.8.0~ynh1"

maintainers = ["JimboJoe"]

[upstream]
license = "GPL-2.0"
website = "http://Discourse.org"
demo = "https://try.discourse.org"
code = "https://github.com/discourse/discourse"
cpe = "cpe:2.3:a:discourse:discourse"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "1G"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/forum"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.sources]
    [resources.sources.main]
    url = "https://github.com/discourse/discourse/archive/refs/tags/v2026.8.0.tar.gz"
    sha256 = "9e5221f49cc7806367b0b44b6d0c4f9615c27515871c3c83e270972fd6e5af93"

    autoupdate.strategy = "latest_github_tag"

    [resources.sources.ldap-auth]
    url = "https://github.com/jonmbake/discourse-ldap-auth/archive/9776c1d021696e5bfdb8857093b8434063bc6ae1.tar.gz"
    sha256 = "6007f2762934f248796a9feef009cab86ff91ad31a49d7bf736479c58520eaee"

    autoupdate.strategy = "latest_github_commit"
    autoupdate.upstream = "https://github.com/jonmbake/discourse-ldap-auth"

    [resources.sources.imagemagickv7]
    amd64.url = "https://github.com/orhtej2/imagemagick-binary/releases/download/7.1.2-30/imagemagick-7.1.2-30-linux-amd64.tar.gz"
    amd64.sha256 = "ed1a7b8427b60471967631d1b0c396fd1c22f10d8d377221f75eacbc3810bdb1"
    arm64.url = "https://github.com/orhtej2/imagemagick-binary/releases/download/7.1.2-30/imagemagick-7.1.2-30-linux-arm64.tar.gz"
    arm64.sha256 = "b7fb04b7e122832c3eea470f504af7ad8d35e1f50a0c55d985886c5e87f20964"
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/orhtej2/imagemagick-binary"
    autoupdate.asset.amd64 = "imagemagick-\\d+\\.\\d+\\.\\d+-\\d+-linux-amd64\\.tar\\.gz$"
    autoupdate.asset.arm64 = "imagemagick-\\d+\\.\\d+\\.\\d+-\\d+-linux-arm64\\.tar\\.gz$"

    [resources.sources.oxipng]
    amd64.url = "https://github.com/oxipng/oxipng/releases/download/v10.2.0/oxipng-10.2.0-x86_64-unknown-linux-gnu.tar.gz"
    amd64.sha256 = "b33f84c73d42cb592bea5d84c431030b1e97784817693380dfcec7d9575f871e"

    arm64.url = "https://github.com/oxipng/oxipng/releases/download/v10.2.0/oxipng-10.2.0-aarch64-unknown-linux-gnu.tar.gz"
    arm64.sha256 = "97d168c6c0d1dbcb36e7438eb489804748a2ba40d94fe21aa7dab7372e9efe9b"

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/shssoichiro/oxipng"
    autoupdate.asset.amd64 = "^oxipng-.*-x86_64-unknown-linux-gnu\\.tar\\.gz$"
    autoupdate.asset.arm64 = "^oxipng-.*-aarch64-unknown-linux-gnu\\.tar\\.gz$"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "advancecomp",
        "brotli",
        "cmake",
        "g++",
        "gifsicle",
        "jhead",
        "jpegoptim",
        "libapr1-dev",
        "libcurl4-openssl-dev",
        "libjemalloc-dev",
        "libjemalloc2",
        "libjpeg-turbo-progs",
        "libpq-dev",
        "libreadline-dev",
        "libssl-dev",
        "libtcmalloc-minimal4",
        "libunwind-dev",
        "libxml2-dev",
        "libxslt1-dev",
        "libyaml-dev",
        "optipng",
        "pngcrush",
        "pngquant",
        "redis-server",
        "zlib1g-dev",
        "libffi-dev",

        "postgresql",
        "postgresql-client",
        "postgresql-contrib",
    ]
    packages_from_raw_bash = """
        if [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
            echo "postgresql-17-pgvector";
        fi
    """
    
    [resources.apt.extras.postgresql]
    repo = "deb https://apt.postgresql.org/pub/repos/apt __YNH_DEBIAN_VERSION__-pgdg main"
    key = "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    packages_from_raw_bash = """
        if [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
            echo "postgresql-15-pgvector";
        else echo "";
        fi
    """

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "22"

    [resources.ruby]
    version = "3.4"
