#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.80071cd67103f95b5438b4a49689e25ff05725cd.name = "Upgrade from 2026.1.0"

