#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

if ! ynh_in_ci_tests; then
    # Check memory requirements
    check_memory_requirements
fi

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

relative_url_root=${path%/}

# Create a random password
admin_pwd=$(ynh_string_random)
admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --key=redis_db --value="$redis_db"

# Set a secret value
secret="$(ynh_string_random)"

# We assume for the moment that ARM devices are only dual core, so
# we restrict the number of workers to 2 (the default is 3)
if dpkg --print-architecture | grep -q "arm"; then
    unicorn_workers=2
else
    unicorn_workers=3
fi
ynh_app_setting_set --key=unicorn_workers --value=$unicorn_workers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

# Building and installing ImageMagick v7
install_imagemagick

# Installing Oxipng
install_oxipng

#=================================================
# CONFIGURE A POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Configuring $app's PostgreSQL database..."

# Set extensions
ynh_psql_db_shell <<< "CREATE EXTENSION IF NOT EXISTS hstore;"
ynh_psql_db_shell <<< "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
ynh_psql_db_shell <<< "CREATE EXTENSION IF NOT EXISTS vector;"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/discourse"

# Install LDAP plugin
ynh_setup_source --source_id=ldap-auth --dest_dir="$install_dir/discourse/plugins/ldap"

# Add a pids and socket directory for the systemd script.
mkdir -p "$install_dir/discourse/tmp/pids"
mkdir -p "$install_dir/discourse/tmp/sockets"
mkdir -p "$install_dir/discourse/public/forum"

# Create specific folders and links for subfolder compatibility
# (see: https://meta.discourse.org/t/subfolder-support-with-docker/30507)
ln -s "$install_dir/discourse/public/uploads" "$install_dir/discourse/public/forum/uploads"
ln -s "$install_dir/discourse/public/backups" "$install_dir/discourse/public/forum/backups"

# Set permissions to app files
chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration file..."

ynh_config_add --template="discourse_defaults.conf" --destination="$install_dir/discourse/config/discourse.conf"
ynh_config_add --template="secrets.yml" --destination="$install_dir/discourse/config/secrets.yml"
ynh_config_add --template="settings.yml" --destination="$install_dir/discourse/plugins/ldap/config/settings.yml"

# Disable svgo worker
echo "svgo: false" | ynh_exec_as_app tee "$install_dir/discourse/.image_optim.yml" >/dev/null

#=================================================
# SETUP UNICORN, A RUBY SERVER
#=================================================
ynh_script_progression "Setting up Unicorn..."

# On ARM architecture, replace bundled libpsl by system native libpsl
# because the provided binary isn't compatible
if dpkg --print-architecture | grep -q "arm"; then
    (
        cd "$install_dir/discourse/vendor/bundle/ruby"/*/"gems/mini_suffix-*/vendor"
        rm libpsl.so
        ln -s "$(ldconfig -p | grep libpsl | awk 'END {print $NF}')" libpsl.so
    )
fi

pushd "$install_dir/discourse"
    # Install bundler, a gems installer
    gem install bundler --conservative -v $(awk '/BUNDLED WITH/ { getline; gsub(/ /,""); print $0 }' $install_dir/discourse/Gemfile.lock)
    # Install without documentation
    echo "gem: --no-ri --no-rdoc" | ynh_exec_as_app tee "$install_dir/discourse/.gemrc" >/dev/null

    # Specific actions on ARM architecture
    if dpkg --print-architecture | grep -q "arm"; then
        # Define the platform specifically to retrieve binaries
        # for libv8 because it currently doesn't compile on ARM devices
        _exec_as_app_with_ruby_node bundle config specific_platform arm-linux
    fi

    # Install dependencies
    _exec_as_app_with_ruby_node bundle config --local path "$install_dir/discourse/vendor/bundle"
    _exec_as_app_with_ruby_node bundle config --local without test development
    _exec_as_app_with_ruby_node bundle install --jobs 2
popd

pushd "$install_dir/discourse"
    ynh_hide_warnings npm install --location=global pnpm@9 --force
    ynh_hide_warnings _exec_as_app_with_ruby_node pnpm install --frozen-lockfile
popd

#=================================================
# PREPARE THE DATABASE
#=================================================
ynh_script_progression "Preparing the database..."

pushd "$install_dir/discourse"
    ynh_hide_warnings _exec_as_app_with_ruby_node RAILS_ENV=production bundle exec rake db:migrate
    ynh_hide_warnings _exec_as_app_with_ruby_node RAILS_ENV=production bundle exec rake themes:update
    ynh_hide_warnings _exec_as_app_with_ruby_node RAILS_ENV=production DISCOURSE_DOWNLOAD_PRE_BUILT_ASSETS=0 bundle exec rake assets:precompile
popd

# Set default data (especially to have correct image URLs for subfolder install)
ynh_config_add --template="provisioning.sql" --destination="$install_dir/provisioning.sql"
ynh_psql_db_shell < "$install_dir/provisioning.sql"
ynh_safe_rm "$install_dir/provisioning.sql"

#=================================================
# CREATE DISCOURSE ADMIN USER
#=================================================
ynh_script_progression "Creating Discourse admin user..."

pushd "$install_dir/discourse"
    _exec_as_app_with_ruby_node RAILS_ENV=production bundle exec rake admin:create <<< "$admin_mail
$admin_pwd
$admin_pwd
y
"
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Reference: https://meta.discourse.org/t/subfolder-support-with-docker/30507?u=falco&source_topic_id=54191
if [ "$path" != "/" ] ; then
    ynh_replace --file="/etc/nginx/conf.d/$domain.d/$app.conf" \
        --match='$proxy_add_x_forwarded_for' \
        --replace='$http_your_original_ip_header'
fi
ynh_store_file_checksum "/etc/nginx/conf.d/$domain.d/$app.conf"

additional_env="UNICORN_WORKERS=$unicorn_workers"

ynh_config_add_systemd
yunohost service add "$app" --log "$install_dir/discourse/log/unicorn.stderr.log" "$install_dir/discourse/log/unicorn.stdout.log" "$install_dir/discourse/log/production.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate "$install_dir/discourse/log/unicorn.stderr.log"
ynh_config_add_logrotate "$install_dir/discourse/log/unicorn.stdout.log"
ynh_config_add_logrotate "$install_dir/discourse/log/production.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="$install_dir/discourse/log/unicorn.stdout.log" --wait_until="INFO -- : worker=$((unicorn_workers-1)) ready"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
