#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
source _common.sh

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
db_name=$(ynh_app_setting_get $app db_name)
final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# STANDARD REMOVE
#=================================================
# STOP AND REMOVE SERVICE
#=================================================

ynh_remove_systemd_config discourse-puma
ynh_remove_systemd_config discourse-sidekiq

# STOP AND REMOVE SERVICE
#=================================================

# Remove the dedicated systemd config
# ynh_remove_systemd_config

# service $app stop
# rm "/etc/init.d/$app"
# update-rc.d -f $app remove

#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

if yunohost service status | grep -q $app
then
	echo "Remove $app services"
	yunohost service remove $app-puma
	yunohost service remove $app-sidekiq
fi

#=================================================
# REMOVE DEPENDENCIES
#=================================================

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# REMOVE THE POSTGRES DATABASE
#=================================================

ynh_psql_remove_db $db_name $db_name

#=================================================
# REMOVE APP MAIN DIR
#=================================================

# Remove the app directory securely
ynh_secure_remove "$final_path"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================

# Remove the dedicated nginx config
ynh_remove_nginx_config

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================

# Remove the app-specific logrotate config
ynh_remove_logrotate

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================

# Delete a system user
ynh_system_user_delete $app
